Fixes to release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,20 +4,25 @@ on:
   push:
     tags:
       - 'v*'
-    branches:
-      - main
 
 jobs:
-  build:
+  release:
     runs-on: ubuntu-latest
     steps:
+      - name: Check Tag Creator
+        run: |
+          if [[ "${{ github.actor }}" != "${{ github.repository_owner }}" ]]; then
+            echo "Error: Tag must be created by ${{ github.repository_owner }}"
+            exit 1
+          fi
+
       - name: Checkout code
         uses: actions/checkout@v3
 
       - name: Setup Go
         uses: actions/setup-go@v3
         with:
-          go-version: 1.17
+          go-version: 1.19
           check-latest: true
 
       - name: Get dependencies
@@ -26,10 +31,6 @@ jobs:
       - name: Build Binary
         run: go build -o suimon
 
-      - name: Read Release Notes
-        id: read_release_notes
-        run: echo "::set-output name=notes::$(cat static/release-notes.txt)"
-
       - name: Create Release
         id: create_release
         uses: actions/create-release@v1
@@ -37,8 +38,8 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           tag_name: ${{ github.ref }}
-          release_name: Suimon Release ${{ github.ref }}
-          body: ${{ steps.read_release_notes.outputs.notes }}
+          release_name: Release ${{ github.ref }}
+          body: ${{ env.RELEASE_NOTES }}
           draft: false
           prerelease: false
 
